---
Name: admin-branding
Before:
  - '#login-forms'
---
SilverStripe\LoginForms\EnablerExtension:
  login_themes:
    # insert before themes in vendor/silverstripe/login-forms/_config/theme.yml
    - 'sunnysideup/branded-login-screen:login-forms'


SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Sunnysideup\BrandedLoginScreen\SiteConfigExtension

SilverStripe\Security\Member:
  extensions:
    - Sunnysideup\BrandedLoginScreen\Authenticators\MemberExtension

SilverStripe\CMS\Controllers\ContentController:
  extensions:
    - Sunnysideup\BrandedLoginScreen\Authenticators\ControllerExtension

SilverStripe\Core\Injector\Injector:
  SilverStripe\Security\Security:
    properties:
      Authenticators:
        pincode: '%$Sunnysideup\BrandedLoginScreen\Authenticators\PincodeAuthenticator'